/**
 * 错误码表（PRD 4.3「错误码表」产物）：前后端共用同一份，前端据此做提示与分支。
 */
export const ErrorCode = {
  /* 通用 */
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  /* 领域 */
  ASSUMPTIONS_PENDING: 'ASSUMPTIONS_PENDING',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CONTRACT_ALREADY_LOCKED: 'CONTRACT_ALREADY_LOCKED',
  CONTRACT_NOT_LOCKED: 'CONTRACT_NOT_LOCKED',
  DEPENDENCIES_NOT_CONFIRMED: 'DEPENDENCIES_NOT_CONFIRMED',
  CYCLE_DETECTED: 'CYCLE_DETECTED',
  NO_REQUIREMENT_DOC: 'NO_REQUIREMENT_DOC',
  NO_REQUIREMENT_ITEMS: 'NO_REQUIREMENT_ITEMS',
  PIPELINE_ALREADY_RUNNING: 'PIPELINE_ALREADY_RUNNING',
  PIPELINE_NOT_RUNNING: 'PIPELINE_NOT_RUNNING',
  ITEM_NOT_RESOLVABLE: 'ITEM_NOT_RESOLVABLE',
  FIX_LIMIT_REACHED: 'FIX_LIMIT_REACHED',
  LLM_ERROR: 'LLM_ERROR',
  SANDBOX_ERROR: 'SANDBOX_ERROR',
  MODEL_NOT_CONFIGURED: 'MODEL_NOT_CONFIGURED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  UNAUTHORIZED: '未登录或登录已过期',
  FORBIDDEN: '无权访问该资源',
  NOT_FOUND: '资源不存在',
  VALIDATION_FAILED: '参数校验失败',
  CONFLICT: '资源冲突',
  INTERNAL_ERROR: '服务内部错误',

  ASSUMPTIONS_PENDING: '假设清单尚未全部处理，无法进入下一阶段',
  CONTRACT_NOT_FOUND: '契约尚未生成',
  CONTRACT_ALREADY_LOCKED: '契约已锁定，不可修改',
  CONTRACT_NOT_LOCKED: '契约未锁定，无法进入依赖编排',
  DEPENDENCIES_NOT_CONFIRMED: '依赖图尚未确认',
  CYCLE_DETECTED: '依赖图中存在循环依赖',
  NO_REQUIREMENT_DOC: '尚未导入需求文档',
  NO_REQUIREMENT_ITEMS: '尚未解析出需求条目',
  PIPELINE_ALREADY_RUNNING: '流水线正在运行中',
  PIPELINE_NOT_RUNNING: '流水线未在运行',
  ITEM_NOT_RESOLVABLE: '该条目当前状态不支持重新执行',
  FIX_LIMIT_REACHED: '已达最大修复轮次，转人工处理',
  LLM_ERROR: '模型调用失败',
  SANDBOX_ERROR: '沙箱执行失败',
  MODEL_NOT_CONFIGURED: '尚未配置可用模型',
}
